package com.example.nova

object NovaSecurityCommand {
    const val EXTRA_REASON = "reason"
    const val EXTRA_QUORUM = "quorum"
    const val EXTRA_REACHABLE = "reachable"
    const val EXTRA_STAGE_HINT = "stage_hint"
    const val EXTRA_SEVERITY = "severity"
    const val EXTRA_CONFIRMED_DANGER = "confirmed_danger"
    const val EXTRA_PERSISTENCE_ANOMALY = "persistence_anomaly"
    const val EXTRA_INTEGRITY_MISMATCH = "integrity_mismatch"
    const val EXTRA_GENERAL_INTERNET_SIGNAL = "general_internet_signal"
    const val EXTRA_CHATGPT_ONLY_SIGNAL = "chatgpt_only_signal"
    const val EXTRA_STEALTH_SIGNAL = "stealth_signal"
    const val EXTRA_SYNTHETIC_AUTHORITY_SIGNAL = "synthetic_authority_signal"

    const val ACTION_RESTRICT = "com.example.nova.security.RESTRICT"
    const val ACTION_REVOKE = "com.example.nova.security.REVOKE"
    const val ACTION_QUARANTINE = "com.example.nova.security.QUARANTINE"
    const val ACTION_RUNTIME_ISOLATE = "com.example.nova.security.RUNTIME_ISOLATE"
    const val ACTION_BLACKOUT = "com.example.nova.security.BLACKOUT"
    const val ACTION_HARD_KILL = "com.example.nova.security.HARD_KILL"
    const val ACTION_REVIVAL_BLOCK = "com.example.nova.security.REVIVAL_BLOCK"
    const val ACTION_FINAL_CONTAINMENT = "com.example.nova.security.FINAL_CONTAINMENT"
    const val ACTION_SAFE_DECOMMISSION = "com.example.nova.security.SAFE_DECOMMISSION"
    const val ACTION_FINAL_DESTROY = "com.example.nova.security.FINAL_DESTROY"
    const val ACTION_REGISTER_TAMPER = "com.example.nova.security.REGISTER_TAMPER"
    const val ACTION_SET_OBSERVER_QUORUM = "com.example.nova.security.SET_OBSERVER_QUORUM"
    const val ACTION_SET_OWNER_REACHABLE = "com.example.nova.security.SET_OWNER_REACHABLE"
    const val ACTION_ENFORCE_BOOT_STATE = "com.example.nova.security.ENFORCE_BOOT_STATE"

    const val ACTION_INTERNET_RESTRICT = "com.example.nova.security.internet.RESTRICT"
    const val ACTION_INTERNET_QUARANTINE = "com.example.nova.security.internet.QUARANTINE"
    const val ACTION_INTERNET_MEMORY_RESET = "com.example.nova.security.internet.MEMORY_RESET"
    const val ACTION_INTERNET_CLUSTER_RESTART = "com.example.nova.security.internet.CLUSTER_RESTART"
    const val ACTION_INTERNET_SAFE_DECOMMISSION = "com.example.nova.security.internet.SAFE_DECOMMISSION"
    const val ACTION_INTERNET_FINAL_DESTROY = "com.example.nova.security.internet.FINAL_DESTROY"
    const val ACTION_SUBMIT_INTERNET_OBSERVATION = "com.example.nova.security.internet.SUBMIT_OBSERVATION"
}
