[modules]
autoload=yes
require = app_audiosocket.so
require = res_audiosocket.so
require = func_uuid.so
require = app_mixmonitor.so
require = chan_pjsip.so
require = res_pjsip.so
require = res_pjsip_outbound_registration.so
