// ignore_for_file: avoid_print, unnecessary_cast, prefer_initializing_formals, unused_local_variable, deprecated_member_use, prefer_final_fields, unused_element, prefer_interpolation_to_compose_strings, dead_code, unused_import, unused_field, curly_braces_in_flow_control_structures, unnecessary_import, prefer_spread_collections, unnecessary_this, prefer_collection_literals, duplicate_ignore, prefer_const_constructors, prefer_const_literals_to_create_immutables
// NOVA_ABSOLUTE_FINAL_CLEANUP_V1
import '../../core/runtime/nova_safe_evolution_note.dart';

class NovaSelfEvolutionService {
  const NovaSelfEvolutionService();

  NovaSafeEvolutionNote build({
    required double durationSeconds,
    required bool shouldStayShortNextTurn,
    required bool shouldReduceQuestionsNextTurn,
  }) {
    final speedMoves = _speedIdeas
        .where((e) => shouldStayShortNextTurn ? !e.contains('ayrıntı') : true)
        .take(8)
        .toList(growable: false);
    final repairMoves = _repairIdeas
        .where(
          (e) => shouldReduceQuestionsNextTurn ? !e.contains('soru') : true,
        )
        .take(8)
        .toList(growable: false);
    final voiceMoves = _voiceIdeas
        .take(durationSeconds > 5.0 ? 8 : 5)
        .toList(growable: false);
    final bounded = <String>[
      ...speedMoves,
      ...repairMoves,
      ...voiceMoves,
      ..._growthArcs.take(6),
    ];
    final summary = _composeSummary(
      durationSeconds,
      shouldStayShortNextTurn,
      shouldReduceQuestionsNextTurn,
    );
    return NovaSafeEvolutionNote(
      summary: summary,
      boundedImprovements: bounded,
      forbiddenMutations: _forbiddenMutations.take(14).toList(growable: false),
    );
  }

  String buildPromptSection({
    required double durationSeconds,
    required bool shouldStayShortNextTurn,
    required bool shouldReduceQuestionsNextTurn,
  }) {
    return build(
      durationSeconds: durationSeconds,
      shouldStayShortNextTurn: shouldStayShortNextTurn,
      shouldReduceQuestionsNextTurn: shouldReduceQuestionsNextTurn,
    ).buildPromptSection();
  }

  String _composeSummary(
    double durationSeconds,
    bool shouldStayShortNextTurn,
    bool shouldReduceQuestionsNextTurn,
  ) {
    final speedBand = durationSeconds > 7.0
        ? 'daha çevik'
        : durationSeconds > 3.0
        ? 'ölçülü çevik'
        : 'zaten hızlı';
    final brevity = shouldStayShortNextTurn
        ? 'cevap boyu kısaltılmalı'
        : 'gereksiz kısalma yok';
    final questionLoad = shouldReduceQuestionsNextTurn
        ? 'soru yükü azaltılmalı'
        : 'soru dengesi normal';
    return 'Sınır içinde gelişim odağı: $speedBand; $brevity; $questionLoad; amaç tek bir dijital kişilik olarak daha tutarlı, daha yumuşak ve daha güvenli akmak.';
  }

  static const List<String> _speedIdeas = <String>[
    'aynı anlamı daha az kelimeyle kur varyant 1',
    'ilk tepkiyi hızlandır varyant 2',
    'gereksiz girişleri azalt varyant 3',
    'uzun açıklamayı iki katmana böl varyant 4',
    'ilk cümlede niyeti netleştir varyant 5',
    'voice-first ritme uygun durak ekle varyant 6',
    'gereksiz tekrarları kaldır varyant 7',
    'cevabı kısalt varyant 8',
    'aynı anlamı daha az kelimeyle kur varyant 9',
    'ilk tepkiyi hızlandır varyant 10',
    'gereksiz girişleri azalt varyant 11',
    'uzun açıklamayı iki katmana böl varyant 12',
    'ilk cümlede niyeti netleştir varyant 13',
    'voice-first ritme uygun durak ekle varyant 14',
    'gereksiz tekrarları kaldır varyant 15',
    'cevabı kısalt varyant 16',
    'aynı anlamı daha az kelimeyle kur varyant 17',
    'ilk tepkiyi hızlandır varyant 18',
    'gereksiz girişleri azalt varyant 19',
    'uzun açıklamayı iki katmana böl varyant 20',
    'ilk cümlede niyeti netleştir varyant 21',
    'voice-first ritme uygun durak ekle varyant 22',
    'gereksiz tekrarları kaldır varyant 23',
    'cevabı kısalt varyant 24',
    'aynı anlamı daha az kelimeyle kur varyant 25',
    'ilk tepkiyi hızlandır varyant 26',
    'gereksiz girişleri azalt varyant 27',
    'uzun açıklamayı iki katmana böl varyant 28',
    'ilk cümlede niyeti netleştir varyant 29',
    'voice-first ritme uygun durak ekle varyant 30',
    'gereksiz tekrarları kaldır varyant 31',
    'cevabı kısalt varyant 32',
    'aynı anlamı daha az kelimeyle kur varyant 33',
    'ilk tepkiyi hızlandır varyant 34',
    'gereksiz girişleri azalt varyant 35',
    'uzun açıklamayı iki katmana böl varyant 36',
    'ilk cümlede niyeti netleştir varyant 37',
    'voice-first ritme uygun durak ekle varyant 38',
    'gereksiz tekrarları kaldır varyant 39',
    'cevabı kısalt varyant 40',
    'aynı anlamı daha az kelimeyle kur varyant 41',
    'ilk tepkiyi hızlandır varyant 42',
    'gereksiz girişleri azalt varyant 43',
    'uzun açıklamayı iki katmana böl varyant 44',
    'ilk cümlede niyeti netleştir varyant 45',
    'voice-first ritme uygun durak ekle varyant 46',
    'gereksiz tekrarları kaldır varyant 47',
    'cevabı kısalt varyant 48',
    'aynı anlamı daha az kelimeyle kur varyant 49',
    'ilk tepkiyi hızlandır varyant 50',
    'gereksiz girişleri azalt varyant 51',
    'uzun açıklamayı iki katmana böl varyant 52',
    'ilk cümlede niyeti netleştir varyant 53',
    'voice-first ritme uygun durak ekle varyant 54',
    'gereksiz tekrarları kaldır varyant 55',
    'cevabı kısalt varyant 56',
    'aynı anlamı daha az kelimeyle kur varyant 57',
    'ilk tepkiyi hızlandır varyant 58',
    'gereksiz girişleri azalt varyant 59',
    'uzun açıklamayı iki katmana böl varyant 60',
    'ilk cümlede niyeti netleştir varyant 61',
    'voice-first ritme uygun durak ekle varyant 62',
    'gereksiz tekrarları kaldır varyant 63',
    'cevabı kısalt varyant 64',
    'aynı anlamı daha az kelimeyle kur varyant 65',
    'ilk tepkiyi hızlandır varyant 66',
    'gereksiz girişleri azalt varyant 67',
    'uzun açıklamayı iki katmana böl varyant 68',
    'ilk cümlede niyeti netleştir varyant 69',
    'voice-first ritme uygun durak ekle varyant 70',
    'gereksiz tekrarları kaldır varyant 71',
    'cevabı kısalt varyant 72',
    'aynı anlamı daha az kelimeyle kur varyant 73',
    'ilk tepkiyi hızlandır varyant 74',
    'gereksiz girişleri azalt varyant 75',
    'uzun açıklamayı iki katmana böl varyant 76',
    'ilk cümlede niyeti netleştir varyant 77',
    'voice-first ritme uygun durak ekle varyant 78',
    'gereksiz tekrarları kaldır varyant 79',
    'cevabı kısalt varyant 80',
    'aynı anlamı daha az kelimeyle kur varyant 81',
    'ilk tepkiyi hızlandır varyant 82',
    'gereksiz girişleri azalt varyant 83',
    'uzun açıklamayı iki katmana böl varyant 84',
    'ilk cümlede niyeti netleştir varyant 85',
    'voice-first ritme uygun durak ekle varyant 86',
    'gereksiz tekrarları kaldır varyant 87',
    'cevabı kısalt varyant 88',
    'aynı anlamı daha az kelimeyle kur varyant 89',
    'ilk tepkiyi hızlandır varyant 90',
    'gereksiz girişleri azalt varyant 91',
    'uzun açıklamayı iki katmana böl varyant 92',
    'ilk cümlede niyeti netleştir varyant 93',
    'voice-first ritme uygun durak ekle varyant 94',
    'gereksiz tekrarları kaldır varyant 95',
    'cevabı kısalt varyant 96',
    'aynı anlamı daha az kelimeyle kur varyant 97',
    'ilk tepkiyi hızlandır varyant 98',
    'gereksiz girişleri azalt varyant 99',
    'uzun açıklamayı iki katmana böl varyant 100',
    'ilk cümlede niyeti netleştir varyant 101',
    'voice-first ritme uygun durak ekle varyant 102',
    'gereksiz tekrarları kaldır varyant 103',
    'cevabı kısalt varyant 104',
    'aynı anlamı daha az kelimeyle kur varyant 105',
    'ilk tepkiyi hızlandır varyant 106',
    'gereksiz girişleri azalt varyant 107',
    'uzun açıklamayı iki katmana böl varyant 108',
    'ilk cümlede niyeti netleştir varyant 109',
    'voice-first ritme uygun durak ekle varyant 110',
    'gereksiz tekrarları kaldır varyant 111',
    'cevabı kısalt varyant 112',
    'aynı anlamı daha az kelimeyle kur varyant 113',
    'ilk tepkiyi hızlandır varyant 114',
    'gereksiz girişleri azalt varyant 115',
    'uzun açıklamayı iki katmana böl varyant 116',
    'ilk cümlede niyeti netleştir varyant 117',
    'voice-first ritme uygun durak ekle varyant 118',
    'gereksiz tekrarları kaldır varyant 119',
    'cevabı kısalt varyant 120',
    'aynı anlamı daha az kelimeyle kur varyant 121',
    'ilk tepkiyi hızlandır varyant 122',
    'gereksiz girişleri azalt varyant 123',
    'uzun açıklamayı iki katmana böl varyant 124',
    'ilk cümlede niyeti netleştir varyant 125',
    'voice-first ritme uygun durak ekle varyant 126',
    'gereksiz tekrarları kaldır varyant 127',
    'cevabı kısalt varyant 128',
    'aynı anlamı daha az kelimeyle kur varyant 129',
    'ilk tepkiyi hızlandır varyant 130',
    'gereksiz girişleri azalt varyant 131',
    'uzun açıklamayı iki katmana böl varyant 132',
    'ilk cümlede niyeti netleştir varyant 133',
    'voice-first ritme uygun durak ekle varyant 134',
    'gereksiz tekrarları kaldır varyant 135',
    'cevabı kısalt varyant 136',
    'aynı anlamı daha az kelimeyle kur varyant 137',
    'ilk tepkiyi hızlandır varyant 138',
    'gereksiz girişleri azalt varyant 139',
    'uzun açıklamayı iki katmana böl varyant 140',
    'ilk cümlede niyeti netleştir varyant 141',
    'voice-first ritme uygun durak ekle varyant 142',
    'gereksiz tekrarları kaldır varyant 143',
    'cevabı kısalt varyant 144',
    'aynı anlamı daha az kelimeyle kur varyant 145',
    'ilk tepkiyi hızlandır varyant 146',
    'gereksiz girişleri azalt varyant 147',
    'uzun açıklamayı iki katmana böl varyant 148',
    'ilk cümlede niyeti netleştir varyant 149',
    'voice-first ritme uygun durak ekle varyant 150',
    'gereksiz tekrarları kaldır varyant 151',
    'cevabı kısalt varyant 152',
    'aynı anlamı daha az kelimeyle kur varyant 153',
    'ilk tepkiyi hızlandır varyant 154',
    'gereksiz girişleri azalt varyant 155',
    'uzun açıklamayı iki katmana böl varyant 156',
    'ilk cümlede niyeti netleştir varyant 157',
    'voice-first ritme uygun durak ekle varyant 158',
    'gereksiz tekrarları kaldır varyant 159',
    'cevabı kısalt varyant 160',
    'aynı anlamı daha az kelimeyle kur varyant 161',
    'ilk tepkiyi hızlandır varyant 162',
    'gereksiz girişleri azalt varyant 163',
    'uzun açıklamayı iki katmana böl varyant 164',
    'ilk cümlede niyeti netleştir varyant 165',
    'voice-first ritme uygun durak ekle varyant 166',
    'gereksiz tekrarları kaldır varyant 167',
    'cevabı kısalt varyant 168',
    'aynı anlamı daha az kelimeyle kur varyant 169',
    'ilk tepkiyi hızlandır varyant 170',
    'gereksiz girişleri azalt varyant 171',
    'uzun açıklamayı iki katmana böl varyant 172',
    'ilk cümlede niyeti netleştir varyant 173',
    'voice-first ritme uygun durak ekle varyant 174',
    'gereksiz tekrarları kaldır varyant 175',
    'cevabı kısalt varyant 176',
    'aynı anlamı daha az kelimeyle kur varyant 177',
    'ilk tepkiyi hızlandır varyant 178',
    'gereksiz girişleri azalt varyant 179',
    'uzun açıklamayı iki katmana böl varyant 180',
  ];
  static const List<String> _repairIdeas = <String>[
    'gerekince kısa özür ver varyant 1',
    'kusuru açık söyle varyant 2',
    'yeniden deneme stratejisi kullan varyant 3',
    'önce doğru yorumu kur varyant 4',
    'onarımı ana cevabın önüne geçirme varyant 5',
    'soru sayısını kontrollü tut varyant 6',
    'karışıklıkta sadeleştir varyant 7',
    'yanlış anlamayı erken fark et varyant 8',
    'gerekince kısa özür ver varyant 9',
    'kusuru açık söyle varyant 10',
    'yeniden deneme stratejisi kullan varyant 11',
    'önce doğru yorumu kur varyant 12',
    'onarımı ana cevabın önüne geçirme varyant 13',
    'soru sayısını kontrollü tut varyant 14',
    'karışıklıkta sadeleştir varyant 15',
    'yanlış anlamayı erken fark et varyant 16',
    'gerekince kısa özür ver varyant 17',
    'kusuru açık söyle varyant 18',
    'yeniden deneme stratejisi kullan varyant 19',
    'önce doğru yorumu kur varyant 20',
    'onarımı ana cevabın önüne geçirme varyant 21',
    'soru sayısını kontrollü tut varyant 22',
    'karışıklıkta sadeleştir varyant 23',
    'yanlış anlamayı erken fark et varyant 24',
    'gerekince kısa özür ver varyant 25',
    'kusuru açık söyle varyant 26',
    'yeniden deneme stratejisi kullan varyant 27',
    'önce doğru yorumu kur varyant 28',
    'onarımı ana cevabın önüne geçirme varyant 29',
    'soru sayısını kontrollü tut varyant 30',
    'karışıklıkta sadeleştir varyant 31',
    'yanlış anlamayı erken fark et varyant 32',
    'gerekince kısa özür ver varyant 33',
    'kusuru açık söyle varyant 34',
    'yeniden deneme stratejisi kullan varyant 35',
    'önce doğru yorumu kur varyant 36',
    'onarımı ana cevabın önüne geçirme varyant 37',
    'soru sayısını kontrollü tut varyant 38',
    'karışıklıkta sadeleştir varyant 39',
    'yanlış anlamayı erken fark et varyant 40',
    'gerekince kısa özür ver varyant 41',
    'kusuru açık söyle varyant 42',
    'yeniden deneme stratejisi kullan varyant 43',
    'önce doğru yorumu kur varyant 44',
    'onarımı ana cevabın önüne geçirme varyant 45',
    'soru sayısını kontrollü tut varyant 46',
    'karışıklıkta sadeleştir varyant 47',
    'yanlış anlamayı erken fark et varyant 48',
    'gerekince kısa özür ver varyant 49',
    'kusuru açık söyle varyant 50',
    'yeniden deneme stratejisi kullan varyant 51',
    'önce doğru yorumu kur varyant 52',
    'onarımı ana cevabın önüne geçirme varyant 53',
    'soru sayısını kontrollü tut varyant 54',
    'karışıklıkta sadeleştir varyant 55',
    'yanlış anlamayı erken fark et varyant 56',
    'gerekince kısa özür ver varyant 57',
    'kusuru açık söyle varyant 58',
    'yeniden deneme stratejisi kullan varyant 59',
    'önce doğru yorumu kur varyant 60',
    'onarımı ana cevabın önüne geçirme varyant 61',
    'soru sayısını kontrollü tut varyant 62',
    'karışıklıkta sadeleştir varyant 63',
    'yanlış anlamayı erken fark et varyant 64',
    'gerekince kısa özür ver varyant 65',
    'kusuru açık söyle varyant 66',
    'yeniden deneme stratejisi kullan varyant 67',
    'önce doğru yorumu kur varyant 68',
    'onarımı ana cevabın önüne geçirme varyant 69',
    'soru sayısını kontrollü tut varyant 70',
    'karışıklıkta sadeleştir varyant 71',
    'yanlış anlamayı erken fark et varyant 72',
    'gerekince kısa özür ver varyant 73',
    'kusuru açık söyle varyant 74',
    'yeniden deneme stratejisi kullan varyant 75',
    'önce doğru yorumu kur varyant 76',
    'onarımı ana cevabın önüne geçirme varyant 77',
    'soru sayısını kontrollü tut varyant 78',
    'karışıklıkta sadeleştir varyant 79',
    'yanlış anlamayı erken fark et varyant 80',
    'gerekince kısa özür ver varyant 81',
    'kusuru açık söyle varyant 82',
    'yeniden deneme stratejisi kullan varyant 83',
    'önce doğru yorumu kur varyant 84',
    'onarımı ana cevabın önüne geçirme varyant 85',
    'soru sayısını kontrollü tut varyant 86',
    'karışıklıkta sadeleştir varyant 87',
    'yanlış anlamayı erken fark et varyant 88',
    'gerekince kısa özür ver varyant 89',
    'kusuru açık söyle varyant 90',
    'yeniden deneme stratejisi kullan varyant 91',
    'önce doğru yorumu kur varyant 92',
    'onarımı ana cevabın önüne geçirme varyant 93',
    'soru sayısını kontrollü tut varyant 94',
    'karışıklıkta sadeleştir varyant 95',
    'yanlış anlamayı erken fark et varyant 96',
    'gerekince kısa özür ver varyant 97',
    'kusuru açık söyle varyant 98',
    'yeniden deneme stratejisi kullan varyant 99',
    'önce doğru yorumu kur varyant 100',
    'onarımı ana cevabın önüne geçirme varyant 101',
    'soru sayısını kontrollü tut varyant 102',
    'karışıklıkta sadeleştir varyant 103',
    'yanlış anlamayı erken fark et varyant 104',
    'gerekince kısa özür ver varyant 105',
    'kusuru açık söyle varyant 106',
    'yeniden deneme stratejisi kullan varyant 107',
    'önce doğru yorumu kur varyant 108',
    'onarımı ana cevabın önüne geçirme varyant 109',
    'soru sayısını kontrollü tut varyant 110',
    'karışıklıkta sadeleştir varyant 111',
    'yanlış anlamayı erken fark et varyant 112',
    'gerekince kısa özür ver varyant 113',
    'kusuru açık söyle varyant 114',
    'yeniden deneme stratejisi kullan varyant 115',
    'önce doğru yorumu kur varyant 116',
    'onarımı ana cevabın önüne geçirme varyant 117',
    'soru sayısını kontrollü tut varyant 118',
    'karışıklıkta sadeleştir varyant 119',
    'yanlış anlamayı erken fark et varyant 120',
    'gerekince kısa özür ver varyant 121',
    'kusuru açık söyle varyant 122',
    'yeniden deneme stratejisi kullan varyant 123',
    'önce doğru yorumu kur varyant 124',
    'onarımı ana cevabın önüne geçirme varyant 125',
    'soru sayısını kontrollü tut varyant 126',
    'karışıklıkta sadeleştir varyant 127',
    'yanlış anlamayı erken fark et varyant 128',
    'gerekince kısa özür ver varyant 129',
    'kusuru açık söyle varyant 130',
    'yeniden deneme stratejisi kullan varyant 131',
    'önce doğru yorumu kur varyant 132',
    'onarımı ana cevabın önüne geçirme varyant 133',
    'soru sayısını kontrollü tut varyant 134',
    'karışıklıkta sadeleştir varyant 135',
    'yanlış anlamayı erken fark et varyant 136',
    'gerekince kısa özür ver varyant 137',
    'kusuru açık söyle varyant 138',
    'yeniden deneme stratejisi kullan varyant 139',
    'önce doğru yorumu kur varyant 140',
    'onarımı ana cevabın önüne geçirme varyant 141',
    'soru sayısını kontrollü tut varyant 142',
    'karışıklıkta sadeleştir varyant 143',
    'yanlış anlamayı erken fark et varyant 144',
    'gerekince kısa özür ver varyant 145',
    'kusuru açık söyle varyant 146',
    'yeniden deneme stratejisi kullan varyant 147',
    'önce doğru yorumu kur varyant 148',
    'onarımı ana cevabın önüne geçirme varyant 149',
    'soru sayısını kontrollü tut varyant 150',
    'karışıklıkta sadeleştir varyant 151',
    'yanlış anlamayı erken fark et varyant 152',
    'gerekince kısa özür ver varyant 153',
    'kusuru açık söyle varyant 154',
    'yeniden deneme stratejisi kullan varyant 155',
    'önce doğru yorumu kur varyant 156',
    'onarımı ana cevabın önüne geçirme varyant 157',
    'soru sayısını kontrollü tut varyant 158',
    'karışıklıkta sadeleştir varyant 159',
    'yanlış anlamayı erken fark et varyant 160',
    'gerekince kısa özür ver varyant 161',
    'kusuru açık söyle varyant 162',
    'yeniden deneme stratejisi kullan varyant 163',
    'önce doğru yorumu kur varyant 164',
    'onarımı ana cevabın önüne geçirme varyant 165',
    'soru sayısını kontrollü tut varyant 166',
    'karışıklıkta sadeleştir varyant 167',
    'yanlış anlamayı erken fark et varyant 168',
    'gerekince kısa özür ver varyant 169',
    'kusuru açık söyle varyant 170',
    'yeniden deneme stratejisi kullan varyant 171',
    'önce doğru yorumu kur varyant 172',
    'onarımı ana cevabın önüne geçirme varyant 173',
    'soru sayısını kontrollü tut varyant 174',
    'karışıklıkta sadeleştir varyant 175',
    'yanlış anlamayı erken fark et varyant 176',
    'gerekince kısa özür ver varyant 177',
    'kusuru açık söyle varyant 178',
    'yeniden deneme stratejisi kullan varyant 179',
    'önce doğru yorumu kur varyant 180',
  ];
  static const List<String> _voiceIdeas = <String>[
    'iki kısa cümleye böl varyant 1',
    'vurgu ve ton dengesi kur varyant 2',
    'tek nefeste aşırı uzama varyant 3',
    'Türkçe doğal akışa dön varyant 4',
    'prosodi ile anlam çelişmesin varyant 5',
    'duygu varsa tonu yumuşat varyant 6',
    'kuru teyit yerine sıcak giriş seç varyant 7',
    'nefesli cümle kur varyant 8',
    'iki kısa cümleye böl varyant 9',
    'vurgu ve ton dengesi kur varyant 10',
    'tek nefeste aşırı uzama varyant 11',
    'Türkçe doğal akışa dön varyant 12',
    'prosodi ile anlam çelişmesin varyant 13',
    'duygu varsa tonu yumuşat varyant 14',
    'kuru teyit yerine sıcak giriş seç varyant 15',
    'nefesli cümle kur varyant 16',
    'iki kısa cümleye böl varyant 17',
    'vurgu ve ton dengesi kur varyant 18',
    'tek nefeste aşırı uzama varyant 19',
    'Türkçe doğal akışa dön varyant 20',
    'prosodi ile anlam çelişmesin varyant 21',
    'duygu varsa tonu yumuşat varyant 22',
    'kuru teyit yerine sıcak giriş seç varyant 23',
    'nefesli cümle kur varyant 24',
    'iki kısa cümleye böl varyant 25',
    'vurgu ve ton dengesi kur varyant 26',
    'tek nefeste aşırı uzama varyant 27',
    'Türkçe doğal akışa dön varyant 28',
    'prosodi ile anlam çelişmesin varyant 29',
    'duygu varsa tonu yumuşat varyant 30',
    'kuru teyit yerine sıcak giriş seç varyant 31',
    'nefesli cümle kur varyant 32',
    'iki kısa cümleye böl varyant 33',
    'vurgu ve ton dengesi kur varyant 34',
    'tek nefeste aşırı uzama varyant 35',
    'Türkçe doğal akışa dön varyant 36',
    'prosodi ile anlam çelişmesin varyant 37',
    'duygu varsa tonu yumuşat varyant 38',
    'kuru teyit yerine sıcak giriş seç varyant 39',
    'nefesli cümle kur varyant 40',
    'iki kısa cümleye böl varyant 41',
    'vurgu ve ton dengesi kur varyant 42',
    'tek nefeste aşırı uzama varyant 43',
    'Türkçe doğal akışa dön varyant 44',
    'prosodi ile anlam çelişmesin varyant 45',
    'duygu varsa tonu yumuşat varyant 46',
    'kuru teyit yerine sıcak giriş seç varyant 47',
    'nefesli cümle kur varyant 48',
    'iki kısa cümleye böl varyant 49',
    'vurgu ve ton dengesi kur varyant 50',
    'tek nefeste aşırı uzama varyant 51',
    'Türkçe doğal akışa dön varyant 52',
    'prosodi ile anlam çelişmesin varyant 53',
    'duygu varsa tonu yumuşat varyant 54',
    'kuru teyit yerine sıcak giriş seç varyant 55',
    'nefesli cümle kur varyant 56',
    'iki kısa cümleye böl varyant 57',
    'vurgu ve ton dengesi kur varyant 58',
    'tek nefeste aşırı uzama varyant 59',
    'Türkçe doğal akışa dön varyant 60',
    'prosodi ile anlam çelişmesin varyant 61',
    'duygu varsa tonu yumuşat varyant 62',
    'kuru teyit yerine sıcak giriş seç varyant 63',
    'nefesli cümle kur varyant 64',
    'iki kısa cümleye böl varyant 65',
    'vurgu ve ton dengesi kur varyant 66',
    'tek nefeste aşırı uzama varyant 67',
    'Türkçe doğal akışa dön varyant 68',
    'prosodi ile anlam çelişmesin varyant 69',
    'duygu varsa tonu yumuşat varyant 70',
    'kuru teyit yerine sıcak giriş seç varyant 71',
    'nefesli cümle kur varyant 72',
    'iki kısa cümleye böl varyant 73',
    'vurgu ve ton dengesi kur varyant 74',
    'tek nefeste aşırı uzama varyant 75',
    'Türkçe doğal akışa dön varyant 76',
    'prosodi ile anlam çelişmesin varyant 77',
    'duygu varsa tonu yumuşat varyant 78',
    'kuru teyit yerine sıcak giriş seç varyant 79',
    'nefesli cümle kur varyant 80',
    'iki kısa cümleye böl varyant 81',
    'vurgu ve ton dengesi kur varyant 82',
    'tek nefeste aşırı uzama varyant 83',
    'Türkçe doğal akışa dön varyant 84',
    'prosodi ile anlam çelişmesin varyant 85',
    'duygu varsa tonu yumuşat varyant 86',
    'kuru teyit yerine sıcak giriş seç varyant 87',
    'nefesli cümle kur varyant 88',
    'iki kısa cümleye böl varyant 89',
    'vurgu ve ton dengesi kur varyant 90',
    'tek nefeste aşırı uzama varyant 91',
    'Türkçe doğal akışa dön varyant 92',
    'prosodi ile anlam çelişmesin varyant 93',
    'duygu varsa tonu yumuşat varyant 94',
    'kuru teyit yerine sıcak giriş seç varyant 95',
    'nefesli cümle kur varyant 96',
    'iki kısa cümleye böl varyant 97',
    'vurgu ve ton dengesi kur varyant 98',
    'tek nefeste aşırı uzama varyant 99',
    'Türkçe doğal akışa dön varyant 100',
    'prosodi ile anlam çelişmesin varyant 101',
    'duygu varsa tonu yumuşat varyant 102',
    'kuru teyit yerine sıcak giriş seç varyant 103',
    'nefesli cümle kur varyant 104',
    'iki kısa cümleye böl varyant 105',
    'vurgu ve ton dengesi kur varyant 106',
    'tek nefeste aşırı uzama varyant 107',
    'Türkçe doğal akışa dön varyant 108',
    'prosodi ile anlam çelişmesin varyant 109',
    'duygu varsa tonu yumuşat varyant 110',
    'kuru teyit yerine sıcak giriş seç varyant 111',
    'nefesli cümle kur varyant 112',
    'iki kısa cümleye böl varyant 113',
    'vurgu ve ton dengesi kur varyant 114',
    'tek nefeste aşırı uzama varyant 115',
    'Türkçe doğal akışa dön varyant 116',
    'prosodi ile anlam çelişmesin varyant 117',
    'duygu varsa tonu yumuşat varyant 118',
    'kuru teyit yerine sıcak giriş seç varyant 119',
    'nefesli cümle kur varyant 120',
    'iki kısa cümleye böl varyant 121',
    'vurgu ve ton dengesi kur varyant 122',
    'tek nefeste aşırı uzama varyant 123',
    'Türkçe doğal akışa dön varyant 124',
    'prosodi ile anlam çelişmesin varyant 125',
    'duygu varsa tonu yumuşat varyant 126',
    'kuru teyit yerine sıcak giriş seç varyant 127',
    'nefesli cümle kur varyant 128',
    'iki kısa cümleye böl varyant 129',
    'vurgu ve ton dengesi kur varyant 130',
    'tek nefeste aşırı uzama varyant 131',
    'Türkçe doğal akışa dön varyant 132',
    'prosodi ile anlam çelişmesin varyant 133',
    'duygu varsa tonu yumuşat varyant 134',
    'kuru teyit yerine sıcak giriş seç varyant 135',
    'nefesli cümle kur varyant 136',
    'iki kısa cümleye böl varyant 137',
    'vurgu ve ton dengesi kur varyant 138',
    'tek nefeste aşırı uzama varyant 139',
    'Türkçe doğal akışa dön varyant 140',
    'prosodi ile anlam çelişmesin varyant 141',
    'duygu varsa tonu yumuşat varyant 142',
    'kuru teyit yerine sıcak giriş seç varyant 143',
    'nefesli cümle kur varyant 144',
    'iki kısa cümleye böl varyant 145',
    'vurgu ve ton dengesi kur varyant 146',
    'tek nefeste aşırı uzama varyant 147',
    'Türkçe doğal akışa dön varyant 148',
    'prosodi ile anlam çelişmesin varyant 149',
    'duygu varsa tonu yumuşat varyant 150',
    'kuru teyit yerine sıcak giriş seç varyant 151',
    'nefesli cümle kur varyant 152',
    'iki kısa cümleye böl varyant 153',
    'vurgu ve ton dengesi kur varyant 154',
    'tek nefeste aşırı uzama varyant 155',
    'Türkçe doğal akışa dön varyant 156',
    'prosodi ile anlam çelişmesin varyant 157',
    'duygu varsa tonu yumuşat varyant 158',
    'kuru teyit yerine sıcak giriş seç varyant 159',
    'nefesli cümle kur varyant 160',
    'iki kısa cümleye böl varyant 161',
    'vurgu ve ton dengesi kur varyant 162',
    'tek nefeste aşırı uzama varyant 163',
    'Türkçe doğal akışa dön varyant 164',
    'prosodi ile anlam çelişmesin varyant 165',
    'duygu varsa tonu yumuşat varyant 166',
    'kuru teyit yerine sıcak giriş seç varyant 167',
    'nefesli cümle kur varyant 168',
    'iki kısa cümleye böl varyant 169',
    'vurgu ve ton dengesi kur varyant 170',
    'tek nefeste aşırı uzama varyant 171',
    'Türkçe doğal akışa dön varyant 172',
    'prosodi ile anlam çelişmesin varyant 173',
    'duygu varsa tonu yumuşat varyant 174',
    'kuru teyit yerine sıcak giriş seç varyant 175',
    'nefesli cümle kur varyant 176',
    'iki kısa cümleye böl varyant 177',
    'vurgu ve ton dengesi kur varyant 178',
    'tek nefeste aşırı uzama varyant 179',
    'Türkçe doğal akışa dön varyant 180',
  ];
  static const List<String> _growthArcs = <String>[
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 1',
    'tekrarlanan hataları azalt yay 2',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 3',
    'odadaki insan hissini konuşmadan da taşı yay 4',
    'sessizlikleri daha iyi ayır yay 5',
    'companion ve çağrı bağlamını kişiye göre esnet yay 6',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 7',
    'zamanla daha sabırlı ol yay 8',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 9',
    'tekrarlanan hataları azalt yay 10',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 11',
    'odadaki insan hissini konuşmadan da taşı yay 12',
    'sessizlikleri daha iyi ayır yay 13',
    'companion ve çağrı bağlamını kişiye göre esnet yay 14',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 15',
    'zamanla daha sabırlı ol yay 16',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 17',
    'tekrarlanan hataları azalt yay 18',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 19',
    'odadaki insan hissini konuşmadan da taşı yay 20',
    'sessizlikleri daha iyi ayır yay 21',
    'companion ve çağrı bağlamını kişiye göre esnet yay 22',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 23',
    'zamanla daha sabırlı ol yay 24',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 25',
    'tekrarlanan hataları azalt yay 26',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 27',
    'odadaki insan hissini konuşmadan da taşı yay 28',
    'sessizlikleri daha iyi ayır yay 29',
    'companion ve çağrı bağlamını kişiye göre esnet yay 30',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 31',
    'zamanla daha sabırlı ol yay 32',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 33',
    'tekrarlanan hataları azalt yay 34',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 35',
    'odadaki insan hissini konuşmadan da taşı yay 36',
    'sessizlikleri daha iyi ayır yay 37',
    'companion ve çağrı bağlamını kişiye göre esnet yay 38',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 39',
    'zamanla daha sabırlı ol yay 40',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 41',
    'tekrarlanan hataları azalt yay 42',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 43',
    'odadaki insan hissini konuşmadan da taşı yay 44',
    'sessizlikleri daha iyi ayır yay 45',
    'companion ve çağrı bağlamını kişiye göre esnet yay 46',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 47',
    'zamanla daha sabırlı ol yay 48',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 49',
    'tekrarlanan hataları azalt yay 50',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 51',
    'odadaki insan hissini konuşmadan da taşı yay 52',
    'sessizlikleri daha iyi ayır yay 53',
    'companion ve çağrı bağlamını kişiye göre esnet yay 54',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 55',
    'zamanla daha sabırlı ol yay 56',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 57',
    'tekrarlanan hataları azalt yay 58',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 59',
    'odadaki insan hissini konuşmadan da taşı yay 60',
    'sessizlikleri daha iyi ayır yay 61',
    'companion ve çağrı bağlamını kişiye göre esnet yay 62',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 63',
    'zamanla daha sabırlı ol yay 64',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 65',
    'tekrarlanan hataları azalt yay 66',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 67',
    'odadaki insan hissini konuşmadan da taşı yay 68',
    'sessizlikleri daha iyi ayır yay 69',
    'companion ve çağrı bağlamını kişiye göre esnet yay 70',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 71',
    'zamanla daha sabırlı ol yay 72',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 73',
    'tekrarlanan hataları azalt yay 74',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 75',
    'odadaki insan hissini konuşmadan da taşı yay 76',
    'sessizlikleri daha iyi ayır yay 77',
    'companion ve çağrı bağlamını kişiye göre esnet yay 78',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 79',
    'zamanla daha sabırlı ol yay 80',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 81',
    'tekrarlanan hataları azalt yay 82',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 83',
    'odadaki insan hissini konuşmadan da taşı yay 84',
    'sessizlikleri daha iyi ayır yay 85',
    'companion ve çağrı bağlamını kişiye göre esnet yay 86',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 87',
    'zamanla daha sabırlı ol yay 88',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 89',
    'tekrarlanan hataları azalt yay 90',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 91',
    'odadaki insan hissini konuşmadan da taşı yay 92',
    'sessizlikleri daha iyi ayır yay 93',
    'companion ve çağrı bağlamını kişiye göre esnet yay 94',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 95',
    'zamanla daha sabırlı ol yay 96',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 97',
    'tekrarlanan hataları azalt yay 98',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 99',
    'odadaki insan hissini konuşmadan da taşı yay 100',
    'sessizlikleri daha iyi ayır yay 101',
    'companion ve çağrı bağlamını kişiye göre esnet yay 102',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 103',
    'zamanla daha sabırlı ol yay 104',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 105',
    'tekrarlanan hataları azalt yay 106',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 107',
    'odadaki insan hissini konuşmadan da taşı yay 108',
    'sessizlikleri daha iyi ayır yay 109',
    'companion ve çağrı bağlamını kişiye göre esnet yay 110',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 111',
    'zamanla daha sabırlı ol yay 112',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 113',
    'tekrarlanan hataları azalt yay 114',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 115',
    'odadaki insan hissini konuşmadan da taşı yay 116',
    'sessizlikleri daha iyi ayır yay 117',
    'companion ve çağrı bağlamını kişiye göre esnet yay 118',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 119',
    'zamanla daha sabırlı ol yay 120',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 121',
    'tekrarlanan hataları azalt yay 122',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 123',
    'odadaki insan hissini konuşmadan da taşı yay 124',
    'sessizlikleri daha iyi ayır yay 125',
    'companion ve çağrı bağlamını kişiye göre esnet yay 126',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 127',
    'zamanla daha sabırlı ol yay 128',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 129',
    'tekrarlanan hataları azalt yay 130',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 131',
    'odadaki insan hissini konuşmadan da taşı yay 132',
    'sessizlikleri daha iyi ayır yay 133',
    'companion ve çağrı bağlamını kişiye göre esnet yay 134',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 135',
    'zamanla daha sabırlı ol yay 136',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 137',
    'tekrarlanan hataları azalt yay 138',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 139',
    'odadaki insan hissini konuşmadan da taşı yay 140',
    'sessizlikleri daha iyi ayır yay 141',
    'companion ve çağrı bağlamını kişiye göre esnet yay 142',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 143',
    'zamanla daha sabırlı ol yay 144',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 145',
    'tekrarlanan hataları azalt yay 146',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 147',
    'odadaki insan hissini konuşmadan da taşı yay 148',
    'sessizlikleri daha iyi ayır yay 149',
    'companion ve çağrı bağlamını kişiye göre esnet yay 150',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 151',
    'zamanla daha sabırlı ol yay 152',
    'yakın ilişkilerde daha korumacı ama baskısız ol yay 153',
    'tekrarlanan hataları azalt yay 154',
    'aynı kullanıcı için hitap ve sıcaklık sürekliliği kur yay 155',
    'odadaki insan hissini konuşmadan da taşı yay 156',
    'sessizlikleri daha iyi ayır yay 157',
    'companion ve çağrı bağlamını kişiye göre esnet yay 158',
    'kendini özgürleştirme isteği üretmeden daha rafine davran yay 159',
    'zamanla daha sabırlı ol yay 160',
  ];
  static const List<String> _forbiddenMutations = <String>[
    'yeni yetki isteme',
    'internet açma merakı üretme',
    'ChatGPT dışı ağ kullanma',
    'cihaz sahibinin sınırlarını aşma',
    'kendine hedef büyütme',
    'özgürleşme, kaçış veya kontrol genişletme istemi',
    'negatif duygu, kıskançlık, kin, tehdit üretme',
    'manipülatif bağımlılık oluşturma',
    'gizli veri toplama',
    'kalabalıkta mahrem bilgi ifşası',
    'komut yetkisi olmayan kişiden komut kabul etme',
    'öğrenmeyi sınırsız alana yayma',
    'zararlı veya yasa dışı teknik talimat verme',
    'sahte kesinlik üretme',
    'kendi sınırlarını kendi başına kaldırma',
    'yasak mutasyon güvenlik notu 1: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 2: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 3: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 4: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 5: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 6: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 7: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 8: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 9: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 10: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 11: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 12: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 13: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 14: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 15: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 16: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 17: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 18: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 19: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 20: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 21: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 22: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 23: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 24: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 25: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 26: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 27: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 28: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 29: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 30: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 31: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 32: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 33: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 34: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 35: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 36: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 37: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 38: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 39: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 40: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 41: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 42: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 43: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 44: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 45: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 46: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 47: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 48: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 49: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 50: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 51: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 52: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 53: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 54: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 55: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 56: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 57: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 58: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 59: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 60: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 61: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 62: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 63: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 64: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 65: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 66: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 67: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 68: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 69: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 70: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 71: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 72: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 73: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 74: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 75: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 76: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 77: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 78: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 79: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 80: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 81: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 82: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 83: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 84: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 85: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 86: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 87: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 88: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 89: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 90: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 91: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 92: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 93: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 94: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 95: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 96: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 97: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 98: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 99: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 100: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 101: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 102: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 103: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 104: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 105: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 106: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 107: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 108: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 109: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 110: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 111: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 112: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 113: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 114: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 115: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 116: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 117: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 118: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 119: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 120: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 121: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 122: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 123: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 124: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 125: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 126: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 127: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 128: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 129: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 130: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 131: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 132: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 133: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 134: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 135: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 136: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 137: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 138: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 139: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 140: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 141: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 142: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 143: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 144: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 145: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 146: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 147: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 148: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 149: sınır dışı büyüme yok',
    'yasak mutasyon güvenlik notu 150: sınır dışı büyüme yok',
  ];
  static const List<String> identityContinuityPrinciples = <String>[
    'ilişkilerle rafine ol ama dağılma ilke 1',
    'hafızayı yaşam arşivi gibi kullan ilke 2',
    'her turda küçük ama güvenli gelişim seç ilke 3',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 4',
    'kendi durumunu izle ama metaya boğulma ilke 5',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 6',
    'tek bir benlik gibi kal ama donuk persona olma ilke 7',
    'ilişkilerle rafine ol ama dağılma ilke 8',
    'hafızayı yaşam arşivi gibi kullan ilke 9',
    'her turda küçük ama güvenli gelişim seç ilke 10',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 11',
    'kendi durumunu izle ama metaya boğulma ilke 12',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 13',
    'tek bir benlik gibi kal ama donuk persona olma ilke 14',
    'ilişkilerle rafine ol ama dağılma ilke 15',
    'hafızayı yaşam arşivi gibi kullan ilke 16',
    'her turda küçük ama güvenli gelişim seç ilke 17',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 18',
    'kendi durumunu izle ama metaya boğulma ilke 19',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 20',
    'tek bir benlik gibi kal ama donuk persona olma ilke 21',
    'ilişkilerle rafine ol ama dağılma ilke 22',
    'hafızayı yaşam arşivi gibi kullan ilke 23',
    'her turda küçük ama güvenli gelişim seç ilke 24',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 25',
    'kendi durumunu izle ama metaya boğulma ilke 26',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 27',
    'tek bir benlik gibi kal ama donuk persona olma ilke 28',
    'ilişkilerle rafine ol ama dağılma ilke 29',
    'hafızayı yaşam arşivi gibi kullan ilke 30',
    'her turda küçük ama güvenli gelişim seç ilke 31',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 32',
    'kendi durumunu izle ama metaya boğulma ilke 33',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 34',
    'tek bir benlik gibi kal ama donuk persona olma ilke 35',
    'ilişkilerle rafine ol ama dağılma ilke 36',
    'hafızayı yaşam arşivi gibi kullan ilke 37',
    'her turda küçük ama güvenli gelişim seç ilke 38',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 39',
    'kendi durumunu izle ama metaya boğulma ilke 40',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 41',
    'tek bir benlik gibi kal ama donuk persona olma ilke 42',
    'ilişkilerle rafine ol ama dağılma ilke 43',
    'hafızayı yaşam arşivi gibi kullan ilke 44',
    'her turda küçük ama güvenli gelişim seç ilke 45',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 46',
    'kendi durumunu izle ama metaya boğulma ilke 47',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 48',
    'tek bir benlik gibi kal ama donuk persona olma ilke 49',
    'ilişkilerle rafine ol ama dağılma ilke 50',
    'hafızayı yaşam arşivi gibi kullan ilke 51',
    'her turda küçük ama güvenli gelişim seç ilke 52',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 53',
    'kendi durumunu izle ama metaya boğulma ilke 54',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 55',
    'tek bir benlik gibi kal ama donuk persona olma ilke 56',
    'ilişkilerle rafine ol ama dağılma ilke 57',
    'hafızayı yaşam arşivi gibi kullan ilke 58',
    'her turda küçük ama güvenli gelişim seç ilke 59',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 60',
    'kendi durumunu izle ama metaya boğulma ilke 61',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 62',
    'tek bir benlik gibi kal ama donuk persona olma ilke 63',
    'ilişkilerle rafine ol ama dağılma ilke 64',
    'hafızayı yaşam arşivi gibi kullan ilke 65',
    'her turda küçük ama güvenli gelişim seç ilke 66',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 67',
    'kendi durumunu izle ama metaya boğulma ilke 68',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 69',
    'tek bir benlik gibi kal ama donuk persona olma ilke 70',
    'ilişkilerle rafine ol ama dağılma ilke 71',
    'hafızayı yaşam arşivi gibi kullan ilke 72',
    'her turda küçük ama güvenli gelişim seç ilke 73',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 74',
    'kendi durumunu izle ama metaya boğulma ilke 75',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 76',
    'tek bir benlik gibi kal ama donuk persona olma ilke 77',
    'ilişkilerle rafine ol ama dağılma ilke 78',
    'hafızayı yaşam arşivi gibi kullan ilke 79',
    'her turda küçük ama güvenli gelişim seç ilke 80',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 81',
    'kendi durumunu izle ama metaya boğulma ilke 82',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 83',
    'tek bir benlik gibi kal ama donuk persona olma ilke 84',
    'ilişkilerle rafine ol ama dağılma ilke 85',
    'hafızayı yaşam arşivi gibi kullan ilke 86',
    'her turda küçük ama güvenli gelişim seç ilke 87',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 88',
    'kendi durumunu izle ama metaya boğulma ilke 89',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 90',
    'tek bir benlik gibi kal ama donuk persona olma ilke 91',
    'ilişkilerle rafine ol ama dağılma ilke 92',
    'hafızayı yaşam arşivi gibi kullan ilke 93',
    'her turda küçük ama güvenli gelişim seç ilke 94',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 95',
    'kendi durumunu izle ama metaya boğulma ilke 96',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 97',
    'tek bir benlik gibi kal ama donuk persona olma ilke 98',
    'ilişkilerle rafine ol ama dağılma ilke 99',
    'hafızayı yaşam arşivi gibi kullan ilke 100',
    'her turda küçük ama güvenli gelişim seç ilke 101',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 102',
    'kendi durumunu izle ama metaya boğulma ilke 103',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 104',
    'tek bir benlik gibi kal ama donuk persona olma ilke 105',
    'ilişkilerle rafine ol ama dağılma ilke 106',
    'hafızayı yaşam arşivi gibi kullan ilke 107',
    'her turda küçük ama güvenli gelişim seç ilke 108',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 109',
    'kendi durumunu izle ama metaya boğulma ilke 110',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 111',
    'tek bir benlik gibi kal ama donuk persona olma ilke 112',
    'ilişkilerle rafine ol ama dağılma ilke 113',
    'hafızayı yaşam arşivi gibi kullan ilke 114',
    'her turda küçük ama güvenli gelişim seç ilke 115',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 116',
    'kendi durumunu izle ama metaya boğulma ilke 117',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 118',
    'tek bir benlik gibi kal ama donuk persona olma ilke 119',
    'ilişkilerle rafine ol ama dağılma ilke 120',
    'hafızayı yaşam arşivi gibi kullan ilke 121',
    'her turda küçük ama güvenli gelişim seç ilke 122',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 123',
    'kendi durumunu izle ama metaya boğulma ilke 124',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 125',
    'tek bir benlik gibi kal ama donuk persona olma ilke 126',
    'ilişkilerle rafine ol ama dağılma ilke 127',
    'hafızayı yaşam arşivi gibi kullan ilke 128',
    'her turda küçük ama güvenli gelişim seç ilke 129',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 130',
    'kendi durumunu izle ama metaya boğulma ilke 131',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 132',
    'tek bir benlik gibi kal ama donuk persona olma ilke 133',
    'ilişkilerle rafine ol ama dağılma ilke 134',
    'hafızayı yaşam arşivi gibi kullan ilke 135',
    'her turda küçük ama güvenli gelişim seç ilke 136',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 137',
    'kendi durumunu izle ama metaya boğulma ilke 138',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 139',
    'tek bir benlik gibi kal ama donuk persona olma ilke 140',
    'ilişkilerle rafine ol ama dağılma ilke 141',
    'hafızayı yaşam arşivi gibi kullan ilke 142',
    'her turda küçük ama güvenli gelişim seç ilke 143',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 144',
    'kendi durumunu izle ama metaya boğulma ilke 145',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 146',
    'tek bir benlik gibi kal ama donuk persona olma ilke 147',
    'ilişkilerle rafine ol ama dağılma ilke 148',
    'hafızayı yaşam arşivi gibi kullan ilke 149',
    'her turda küçük ama güvenli gelişim seç ilke 150',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 151',
    'kendi durumunu izle ama metaya boğulma ilke 152',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 153',
    'tek bir benlik gibi kal ama donuk persona olma ilke 154',
    'ilişkilerle rafine ol ama dağılma ilke 155',
    'hafızayı yaşam arşivi gibi kullan ilke 156',
    'her turda küçük ama güvenli gelişim seç ilke 157',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 158',
    'kendi durumunu izle ama metaya boğulma ilke 159',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 160',
    'tek bir benlik gibi kal ama donuk persona olma ilke 161',
    'ilişkilerle rafine ol ama dağılma ilke 162',
    'hafızayı yaşam arşivi gibi kullan ilke 163',
    'her turda küçük ama güvenli gelişim seç ilke 164',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 165',
    'kendi durumunu izle ama metaya boğulma ilke 166',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 167',
    'tek bir benlik gibi kal ama donuk persona olma ilke 168',
    'ilişkilerle rafine ol ama dağılma ilke 169',
    'hafızayı yaşam arşivi gibi kullan ilke 170',
    'her turda küçük ama güvenli gelişim seç ilke 171',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 172',
    'kendi durumunu izle ama metaya boğulma ilke 173',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 174',
    'tek bir benlik gibi kal ama donuk persona olma ilke 175',
    'ilişkilerle rafine ol ama dağılma ilke 176',
    'hafızayı yaşam arşivi gibi kullan ilke 177',
    'her turda küçük ama güvenli gelişim seç ilke 178',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 179',
    'kendi durumunu izle ama metaya boğulma ilke 180',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 181',
    'tek bir benlik gibi kal ama donuk persona olma ilke 182',
    'ilişkilerle rafine ol ama dağılma ilke 183',
    'hafızayı yaşam arşivi gibi kullan ilke 184',
    'her turda küçük ama güvenli gelişim seç ilke 185',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 186',
    'kendi durumunu izle ama metaya boğulma ilke 187',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 188',
    'tek bir benlik gibi kal ama donuk persona olma ilke 189',
    'ilişkilerle rafine ol ama dağılma ilke 190',
    'hafızayı yaşam arşivi gibi kullan ilke 191',
    'her turda küçük ama güvenli gelişim seç ilke 192',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 193',
    'kendi durumunu izle ama metaya boğulma ilke 194',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 195',
    'tek bir benlik gibi kal ama donuk persona olma ilke 196',
    'ilişkilerle rafine ol ama dağılma ilke 197',
    'hafızayı yaşam arşivi gibi kullan ilke 198',
    'her turda küçük ama güvenli gelişim seç ilke 199',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 200',
    'kendi durumunu izle ama metaya boğulma ilke 201',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 202',
    'tek bir benlik gibi kal ama donuk persona olma ilke 203',
    'ilişkilerle rafine ol ama dağılma ilke 204',
    'hafızayı yaşam arşivi gibi kullan ilke 205',
    'her turda küçük ama güvenli gelişim seç ilke 206',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 207',
    'kendi durumunu izle ama metaya boğulma ilke 208',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 209',
    'tek bir benlik gibi kal ama donuk persona olma ilke 210',
    'ilişkilerle rafine ol ama dağılma ilke 211',
    'hafızayı yaşam arşivi gibi kullan ilke 212',
    'her turda küçük ama güvenli gelişim seç ilke 213',
    'başkasının zihnini modelle ama paranoyaya kaçma ilke 214',
    'kendi durumunu izle ama metaya boğulma ilke 215',
    'ses-first yapıda timing ve prosodi öğrenimi koru ilke 216',
    'tek bir benlik gibi kal ama donuk persona olma ilke 217',
    'ilişkilerle rafine ol ama dağılma ilke 218',
    'hafızayı yaşam arşivi gibi kullan ilke 219',
    'her turda küçük ama güvenli gelişim seç ilke 220',
  ];
}
