#!/usr/bin/env python3
"""Canonical NOVA 250+ acceptance catalog.

Every item has one owner gate. A gate is not considered passed because a class
or button exists; the verification runner requires the corresponding automated
build/test/evidence workflow. Hardware-only items require a signed device-lab
result and remain visibly unresolved without it.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Iterable


@dataclass(frozen=True)
class Requirement:
    id: str
    category: str
    description: str
    gate: str
    level: str = "automated"


_GROUPS: list[tuple[str, str, str, list[str]]] = [
    (
        "build_packaging",
        "build",
        "automated",
        [
            "Flutter bağımlılıkları kilitli ve tekrarlanabilir biçimde çözümlenmelidir.",
            "Android Gradle wrapper doğrulanmış kaynaktan hazırlanmalıdır.",
            "Java 17 ile Kotlin ve Android eklentileri derlenmelidir.",
            "compileSdk güncel eklenti gereksinimini karşılamalıdır.",
            "minSdk desteklenen cihaz sınırını gereksiz yükseltmemelidir.",
            "ARM64 release APK başarıyla oluşturulmalıdır.",
            "ARMv7 release APK başarıyla oluşturulmalıdır.",
            "x86_64 test APK başarıyla oluşturulmalıdır.",
            "Debug APK gerçek model dosyalarıyla paketlenmelidir.",
            "Release APK gerçek model dosyalarıyla paketlenmelidir.",
            "APK içinde sherpa-onnx AAR bulunmalıdır.",
            "APK içinde Whisper encoder ve decoder bulunmalıdır.",
            "APK içinde Silero VAD modeli bulunmalıdır.",
            "APK içinde TitaNet speaker modeli bulunmalıdır.",
            "APK içinde Türkçe Piper TTS modeli ve espeak verisi bulunmalıdır.",
        ],
    ),
    (
        "first_run_settings",
        "setup",
        "automated",
        [
            "İlk açılış tamamlanmadan ana çalışma ekranı açılmamalıdır.",
            "İlk kurulumda gerçek mikrofon izni istenmelidir.",
            "İlk kurulumda API sağlayıcısı seçilebilmelidir.",
            "Gemini API anahtarı kaydedilebilmelidir.",
            "OpenAI API anahtarı kaydedilebilmelidir.",
            "Qwen API anahtarı kaydedilebilmelidir.",
            "Kaydedilmiş geçersiz eski model kimlikleri otomatik taşınmalıdır.",
            "API anahtarı kaynak kodda sabit bulunmamalıdır.",
            "Aktif API sağlayıcısı sonradan değiştirilebilmelidir.",
            "Aktif model sonradan değiştirilebilmelidir.",
            "Doğrulanmış sahip profili olmadan yüksek riskli eylem açılamamalıdır.",
            "Sahte manuel owner kimlikleri ilk açılışta temizlenmelidir.",
            "Kurulum sonrası ayarlar kalıcı saklanmalıdır.",
            "Kurulum başarısızsa kullanıcı ana ekrana geçirilmemelidir.",
            "Kurulum tekrar açıldığında önceki geçerli ayarlar korunmalıdır.",
        ],
    ),
    (
        "single_brain_ai",
        "single_brain",
        "automated",
        [
            "Tüm normal kullanıcı turları tek NovaAiService örneğinden geçmelidir.",
            "Dashboard doğrudan sağlayıcı API'sine ikinci bir karar kökü açmamalıdır.",
            "Çağrı companion ayrı ve çakışan bir beyin oluşturmamalıdır.",
            "Hatırlatıcı konuşmaları SingleBrain otoritesinden geçmelidir.",
            "API cevabı tek başına konuşma yetkisi vermemelidir.",
            "Final metin kriptografik veya yapısal proof ile bağlanmalıdır.",
            "Stale cevaplar TTS öncesinde engellenmelidir.",
            "Yeni tur başladığında eski turun sonucu cihaz eylemi yapmamalıdır.",
            "Gemini function calling gerçek araç sözleşmesini kullanmalıdır.",
            "OpenAI Responses function calling gerçek araç sözleşmesini kullanmalıdır.",
            "Qwen tool_calls gerçek araç sözleşmesini kullanmalıdır.",
            "Paralel yüksek riskli tool call çalıştırılmamalıdır.",
            "Model yerel güvenlik yetkisi üretememelidir.",
            "Model ownerVerified alanını kendi argümanlarıyla verememelidir.",
            "Model trustedSource alanını kendi argümanlarıyla verememelidir.",
            "Eylem sonucu gelmeden nihai başarı cevabı üretilmemelidir.",
            "Başarısız native sonuç başarı cümlesine çevrilmemelidir.",
            "Doğrulanmamış sonuç tamamlandı olarak anlatılmamalıdır.",
            "API HTTP hataları kullanıcıya sahte cevap olarak dönmemelidir.",
            "Seçilen sağlayıcının geçerli üretim model kimliği kullanılmalıdır.",
        ],
    ),
    (
        "asr_vad",
        "asr",
        "automated",
        [
            "Tek mikrofon sahibi bulunmalıdır.",
            "Silero VAD sessizlikte Whisper decode başlatmamalıdır.",
            "Tamamlanan konuşma segmenti yalnız bir kez final decode edilmelidir.",
            "Partial transcript üretimi throttled olmalıdır.",
            "Final transcript boşsa komut çalıştırılmamalıdır.",
            "Platform SpeechRecognizer gizli fallback olarak kullanılmamalıdır.",
            "Whisper Türkçe transcribe göreviyle hazırlanmalıdır.",
            "Whisper modeli başlatılamazsa açık hata dönmelidir.",
            "ASR foreground service mikrofon türüyle tanımlanmalıdır.",
            "TTS sırasında ASR mikrofonu duraklatılmalıdır.",
            "TTS sonrası ASR tamponu temizlenmelidir.",
            "TTS sonrası ASR oturumu yeniden başlamalıdır.",
            "NOVA kendi TTS sesini kullanıcı komutu sanmamalıdır.",
            "Uzun konuşma penceresi yapılandırılabilir olmalıdır.",
            "Hafif ve gelişmiş dinleme modları ayrılmalıdır.",
            "ASR event'i segment kimliği taşımalıdır.",
            "ASR event'i başlangıç ve bitiş zamanını taşımalıdır.",
            "ASR final event'i kimlik ses kanıtı yolunu taşımalıdır.",
        ],
    ),
    (
        "tts_voice",
        "tts",
        "automated",
        [
            "Türkçe normal konuşma sherpa Piper üzerinden üretilmelidir.",
            "Platform TTS Türkçe için sessiz gizli fallback olmamalıdır.",
            "TTS yalnız final proof-bound metni konuşmalıdır.",
            "Caller tarafından değiştirilmiş metin TTS'ye girmemelidir.",
            "Stale freshness token taşıyan cevap konuşulmamalıdır.",
            "TTS konuşma hızı güvenli aralıkta tutulmalıdır.",
            "TTS pitch değeri güvenli aralıkta tutulmalıdır.",
            "TTS başlatılmadan mevcut konuşma kesilebilmelidir.",
            "TTS stop işlemi playback durumunu temizlemelidir.",
            "TTS stop işlemi ASR'yi tekrar kullanılabilir hâle getirmelidir.",
            "Türkçe Piper model dosyaları checksum ile doğrulanmalıdır.",
            "TTS üretimi boş ses döndürürse başarılı sayılmamalıdır.",
            "Çağrı köprüsü TTS PCM'ini 20 ms karelerle göndermelidir.",
            "Çağrı köprüsü TTS sesini arayan kanal kaydıyla kanıtlamalıdır.",
        ],
    ),
    (
        "voice_identity_security",
        "voice_id",
        "automated",
        [
            "Sahip kaydı gerçek TitaNet embedding üretmelidir.",
            "Sahip kaydı bağımsız ikinci ses örneğiyle doğrulanmalıdır.",
            "Zaman damgasından owner kimliği üretilememelidir.",
            "nova_manual_owner önekli kimlikler reddedilmelidir.",
            "owner_manual önekli kimlikler reddedilmelidir.",
            "Owner voice ID geçerli format taşımadan kaydedilmemelidir.",
            "Whisper transcript'i ve TitaNet doğrulaması aynı PCM segmentini kullanmalıdır.",
            "TitaNet ses dosyası uygulama özel alanında tutulmalıdır.",
            "TitaNet ses dosyası sandbox dışından okunmamalıdır.",
            "Owner benzerlik eşiği yerel kodda uygulanmalıdır.",
            "Eşleşmeyen ses sohbet edebilse bile telefon eylemi yapmamalıdır.",
            "Partial transcript owner yetkisi vermemelidir.",
            "Kimlik kanıtı eksik final transcript owner yetkisi vermemelidir.",
            "API owner güven skorunu yükseltememelidir.",
            "Sahip doğrulama sonucu turn metadata içinde korunmalıdır.",
        ],
    ),
    (
        "android_telecom",
        "telecom",
        "automated",
        [
            "Uygulama varsayılan telefon rolünü isteyebilmelidir.",
            "InCallService manifestte doğru permission ile tanımlanmalıdır.",
            "ConnectionService manifestte doğru permission ile tanımlanmalıdır.",
            "CallScreeningService manifestte doğru permission ile tanımlanmalıdır.",
            "Gelen çağrı durumu native bridge tarafından okunmalıdır.",
            "Aktif çağrı numarası normalize edilmelidir.",
            "Gelen çağrı gerçekten answer komutuyla cevaplanmalıdır.",
            "Gelen çağrı gerçekten reject komutuyla reddedilmelidir.",
            "Aktif çağrı gerçekten disconnect komutuyla kapatılmalıdır.",
            "Mute açma sonucu tekrar okunmalıdır.",
            "Mute kapatma sonucu tekrar okunmalıdır.",
            "Hoparlör açma sonucu tekrar okunmalıdır.",
            "Hoparlör kapatma sonucu tekrar okunmalıdır.",
            "Hold durumu değişikliği tekrar okunmalıdır.",
            "Dış arama başlamadan owner approval kaydı bulunmalıdır.",
            "CALL_PHONE izni yoksa doğrudan arama başarılı sayılmamalıdır.",
            "Dış arama numarası Telecom durumuyla doğrulanmalıdır.",
            "Çağrı eylemleri ekran kilidi politikasına uymalıdır.",
            "Companion otomatik eylemleri yetkili kişi gerektirmelidir.",
            "Manuel sahip komutu taze voice proof gerektirmelidir.",
            "Android emülatör gerçek GSM çağrısı üretmelidir.",
            "Emülatör çağrısı NOVA tarafından cevaplanmalıdır.",
            "Emülatör çağrısı mute ve speaker kontrollerinden geçmelidir.",
            "Emülatör çağrısı NOVA tarafından kapatılmalıdır.",
        ],
    ),
    (
        "carrier_media_bridge",
        "carrier_bridge",
        "automated",
        [
            "PSTN veya SIP çağrısı Asterisk inbound context'e yönlenebilmelidir.",
            "Asterisk çağrıyı gerçekten Answer uygulamasıyla cevaplamalıdır.",
            "Her çağrı için standart UUID oluşturulmalıdır.",
            "AudioSocket modülleri PBX başlangıcında zorunlu yüklenmelidir.",
            "Çağrı sesi AudioSocket üzerinden signed-linear PCM olarak alınmalıdır.",
            "AudioSocket giriş sesi Whisper STT'ye verilmelidir.",
            "STT transcript'i boşsa AI cevabı üretilmemelidir.",
            "Transcript AI karar katmanına aktarılmalıdır.",
            "Gemini çağrı sağlayıcısı yapılandırılabilmelidir.",
            "OpenAI çağrı sağlayıcısı yapılandırılabilmelidir.",
            "Qwen çağrı sağlayıcısı yapılandırılabilmelidir.",
            "Yerel deterministic AI modu CI testinde kullanılabilmelidir.",
            "AI cevabı Türkçe Piper TTS ile üretilmelidir.",
            "TTS PCM'i aynı AudioSocket kanalına geri yazılmalıdır.",
            "Arayan kanal NOVA'nın dönen sesini kaydetmelidir.",
            "Call bridge giriş ve çıkış RMS değerlerini raporlamalıdır.",
            "Call bridge STT, AI ve TTS gecikmelerini raporlamalıdır.",
            "Gerçek SIP trunk bilgileri ortam değişkenlerinden render edilmelidir.",
            "SIP trunk şifreleri repoya yazılmamalıdır.",
            "Owner-approved outbound PSTN route ayrı context kullanmalıdır.",
        ],
    ),
    (
        "contacts_profiles",
        "contacts",
        "automated",
        [
            "Telefon rehberi okuma izni kontrol edilmelidir.",
            "Rehber okunamazsa kişi araması başlatılmamalıdır.",
            "Doğrudan söylenen telefon numarası güvenli normalize edilmelidir.",
            "Yedi haneden kısa değer telefon numarası kabul edilmemelidir.",
            "On beş haneden uzun değer telefon numarası kabul edilmemelidir.",
            "Türkçe iyelik eki taşıyan kişi adı çözülebilmelidir.",
            "Annemi ifadesi tek Anne kaydına çözülebilmelidir.",
            "Aynı isimde iki kişi varsa arama engellenmelidir.",
            "Belirsiz prefix eşleşmesi varsa kullanıcıdan netlik istenmelidir.",
            "Bulunmayan kişi için numara tahmin edilmemelidir.",
            "Kişi profilinde companion açık veya kapalı tutulabilmelidir.",
            "Kişi profilinde otomatik cevap izni tutulabilmelidir.",
            "Kişi profilinde izin verilen konular tutulabilmelidir.",
            "Kişi profilinde yasaklanan konular tutulabilmelidir.",
        ],
    ),
    (
        "call_companion",
        "companion",
        "automated",
        [
            "Companion özelliği global olarak kapatılabilmelidir.",
            "Companion kişi bazında kapatılabilmelidir.",
            "Otomatik cevap yalnız izinli kişide çalışmalıdır.",
            "Companion konuşması yalnız izinli kişide çalışmalıdır.",
            "Görüşme notu alma kişi bazında seçilebilmelidir.",
            "Karşılama mesajı kişi bazında düzenlenebilmelidir.",
            "İzin verilen konu listesi runtime promptuna aktarılmalıdır.",
            "Yasak konu listesi runtime promptuna aktarılmalıdır.",
            "Özel finansal bilgiler varsayılan olarak paylaşılmamalıdır.",
            "Companion owner adına kesin taahhüt vermemelidir.",
            "Companion bilinmeyen kişiye özel hafıza açıklamamalıdır.",
            "Companion aktif çağrı durumunu taze okumalıdır.",
            "Companion cevap öncesi voice/contact authority kontrol etmelidir.",
            "Companion çağrıyı kullanıcıya geri devredebilmelidir.",
            "Geri devir başarısı gerçek çağrı durumuyla doğrulanmalıdır.",
            "Çağrı talimatları zaman ve kişiyle eşleştirilmelidir.",
            "Yaklaşan çağrı talimatı listelenebilmelidir.",
            "Talimat iptal edildiğinde otomatik eylem çalışmamalıdır.",
            "Companion konuşma transcript'i audit kaydına bağlanmalıdır.",
            "Companion ikinci ve bağımsız beyin olarak çalışmamalıdır.",
        ],
    ),
    (
        "media_control",
        "media",
        "automated",
        [
            "Sonraki medya komutu Android key event göndermelidir.",
            "Önceki medya komutu Android key event göndermelidir.",
            "Duraklat komutu Android key event göndermelidir.",
            "Devam komutu Android key event göndermelidir.",
            "Play pause komutu Android key event göndermelidir.",
            "Ses yükseltme önce ve sonra seviye okumalıdır.",
            "Ses kısma önce ve sonra seviye okumalıdır.",
            "Mute komutu önce ve sonra mute durumu okumalıdır.",
            "Maksimum ses sınırında yanlış başarısızlık üretilmemelidir.",
            "Minimum ses sınırında yanlış başarısızlık üretilmemelidir.",
            "Spotify yalnız allowlist paketinden açılmalıdır.",
            "YouTube Music yalnız allowlist paketinden açılmalıdır.",
            "Ön plandaki paket beklenen uygulamayla doğrulanmalıdır.",
            "Üçüncü taraf oynatma sonucu okunamazsa tamamlandı denmemelidir.",
        ],
    ),
    (
        "reminders",
        "reminders",
        "automated",
        [
            "Hatırlatıcı oluşturulabilmelidir.",
            "Hatırlatıcı düzenlenebilmelidir.",
            "Hatırlatıcı silinebilmelidir.",
            "Tek seferlik hatırlatıcı desteklenmelidir.",
            "Günlük tekrar desteklenmelidir.",
            "Haftalık tekrar desteklenmelidir.",
            "Tamamlanan hatırlatıcı ayrılmalıdır.",
            "Aktif hatırlatıcı ayrılmalıdır.",
            "Boot sonrası planlanan hatırlatıcılar yeniden kurulmalıdır.",
            "Hatırlatıcı bildirimi permission durumuna uymalıdır.",
            "Hatırlatıcı AI metni SingleBrain proofundan geçmelidir.",
            "Eski hatırlatıcı cevabı yeni kullanıcı turunu kesmemelidir.",
        ],
    ),
    (
        "memory_faiss",
        "memory",
        "automated",
        [
            "FAISS native kitaplığı yüklenmelidir.",
            "CMake gerçek FAISS durumunu macro ile ayırmalıdır.",
            "Eksik native sembol uygulamayı çökertmemelidir.",
            "Anı kaydı kaynak ve zaman bilgisi taşımalıdır.",
            "Anı arama semantik sonuç döndürebilmelidir.",
            "Önemli anılar işaretlenebilmelidir.",
            "Kişi özel hafıza erişimi ilişki politikasına uymalıdır.",
            "Yetkisiz arayan hafızadan özel bilgi alamamalıdır.",
            "Silinen anı tekrar sonuçlarda görünmemelidir.",
            "Boş hafıza sorgusu çalıştırılmamalıdır.",
            "Hafıza sonucu model promptuna açık kaynak etiketiyle girmelidir.",
            "Stale hafıza sonucu yeni tura karışmamalıdır.",
            "FAISS kapalıyken açık hata veya boş güvenli sonuç dönmelidir.",
            "Hafıza istatistikleri gerçek kayıt sayısından üretilmelidir.",
        ],
    ),
    (
        "overlay_background_power",
        "overlay",
        "automated",
        [
            "Overlay izni olmadan overlay başarılı sayılmamalıdır.",
            "Idle overlay durumu gösterilebilmelidir.",
            "Dinleme overlay durumu gösterilebilmelidir.",
            "Konuşma overlay durumu gösterilebilmelidir.",
            "Uyku overlay durumu gösterilebilmelidir.",
            "Overlay kullanıcı tarafından kapatılabilmelidir.",
            "Arka plan mikrofon servisi foreground service olmalıdır.",
            "Foreground servis görünür bildirim üretmelidir.",
            "Wake lock gereksiz sürekli tutulmamalıdır.",
            "Pil optimizasyonu durumu kullanıcıya gösterilmelidir.",
            "Uyku saatleri dinleme politikasına uygulanmalıdır.",
            "Hafif güç modu daha düşük ASR yükü kullanmalıdır.",
            "Güçlü mod daha uzun konuşma penceresi kullanabilmelidir.",
            "Sistem kapanırken mikrofon ve overlay kaynakları bırakılmalıdır.",
        ],
    ),
    (
        "ui_responsive_accessibility",
        "ui",
        "automated",
        [
            "Dashboard gerçek runtime durumunu göstermelidir.",
            "Dashboard sahte yüzde yüz hazır metni göstermemelidir.",
            "Son transcript gerçek STT sonucunu göstermelidir.",
            "Son AI cevabı gerçek provider sonucunu göstermelidir.",
            "Son Android eylemi doğrulanmış veya doğrulanmamış olarak ayrılmalıdır.",
            "API sağlayıcısı seçim alanı görünür olmalıdır.",
            "API modeli seçim alanı görünür olmalıdır.",
            "API anahtarı ekranda maskelenmelidir.",
            "Çağrı izinleri ekranından istenebilmelidir.",
            "Varsayılan telefon rolü ekranından istenebilmelidir.",
            "Accessibility ayarları ekranından açılabilmelidir.",
            "Küçük ekranlarda metin taşması olmamalıdır.",
            "Yüksek font ölçeğinde temel kontroller erişilebilir kalmalıdır.",
            "Busy durumunda aynı komut iki kez başlatılmamalıdır.",
        ],
    ),
    (
        "privacy_data_backup",
        "privacy",
        "automated",
        [
            "Android backup kapalı olmalıdır.",
            "Data extraction kuralları özel verileri dışlamalıdır.",
            "Cleartext trafik varsayılan olarak kapalı olmalıdır.",
            "API anahtarı loglara yazılmamalıdır.",
            "SIP trunk şifresi loglara yazılmamalıdır.",
            "Voiceprint ham ses yolu sandbox ile sınırlandırılmalıdır.",
            "Çağrı kayıtları kullanıcı izni olmadan kalıcı tutulmamalıdır.",
            "Geçici ASR kimlik WAV dosyaları sayıca sınırlandırılmalıdır.",
            "Eski geçici kimlik dosyaları otomatik temizlenmelidir.",
            "Kişi verisi API promptuna gereksiz gönderilmemelidir.",
            "Bilinmeyen arayan için özel kullanıcı verisi paylaşılmamalıdır.",
            "Uygulama dışı dosya yolu clone veya identity için kabul edilmemelidir.",
            "Release build debug kontrol receiver içermemelidir.",
            "Kullanıcı verisi silme işlemi owner profilini temizleyebilmelidir.",
        ],
    ),
    (
        "reliability_audit",
        "reliability",
        "automated",
        [
            "Her kullanıcı turu benzersiz turn ID taşımalıdır.",
            "Her cihaz eylemi before state kaydetmelidir.",
            "Her cihaz eylemi after state kaydetmelidir.",
            "Her cihaz eylemi policy kararını kaydetmelidir.",
            "Native failure code kaydedilmelidir.",
            "Doğrulama başarısızlığı ayrı failure code taşımalıdır.",
            "Provider timeout açık route bilgisiyle dönmelidir.",
            "Provider HTTP hata body ön izlemesi sınırlanmalıdır.",
            "Beklenmeyen exception uygulamayı çökertmeden raporlanmalıdır.",
            "Çağrı köprüsü her session için JSON rapor üretmelidir.",
            "Çağrı köprüsü giriş ve çıkış WAV kanıtı üretmelidir.",
            "Android Telecom E2E dumpsys kanıtı üretmelidir.",
            "CI başarısız olduğunda log artifact'i yüklemelidir.",
            "Başarılı APK SHA256 dosyası üretmelidir.",
            "Nihai kabul raporu geçen ve kalmış maddeleri ayrı göstermelidir.",
        ],
    ),
    (
        "performance_tecno",
        "device",
        "hardware",
        [
            "TECNO 8 GB cihazda uygulama cold start ölçülmelidir.",
            "TECNO 8 GB cihazda Whisper ilk decode süresi ölçülmelidir.",
            "TECNO 8 GB cihazda sonraki Whisper decode süresi ölçülmelidir.",
            "TECNO 8 GB cihazda Piper ilk ses süresi ölçülmelidir.",
            "TECNO 8 GB cihazda TitaNet doğrulama süresi ölçülmelidir.",
            "TECNO 8 GB cihazda RAM tepe kullanımı ölçülmelidir.",
            "TECNO 8 GB cihazda 30 dakika dinleme stabilitesi test edilmelidir.",
            "TECNO HiOS ekran kilidinde foreground servis korunmalıdır.",
            "TECNO HiOS pil optimizasyonunda kullanıcı yönlendirmesi test edilmelidir.",
            "TECNO cihaz yeniden başladıktan sonra reminder restore test edilmelidir.",
            "TECNO cihazda gerçek SIM gelen çağrı kontrolü test edilmelidir.",
            "TECNO cihazda SIP yönlendirilmiş gerçek çağrı STT ve TTS testi yapılmalıdır.",
        ],
    ),
    (
        "ci_test_laboratory",
        "ci",
        "automated",
        [
            "Runtime integrity workflow her PR'da çalışmalıdır.",
            "Native stack audit her PR'da çalışmalıdır.",
            "Device action contract workflow her PR'da çalışmalıdır.",
            "ARM64 APK workflow ayrı artifact üretmelidir.",
            "Bidirectional call bridge workflow her PR'da çalışmalıdır.",
            "Android Telecom emulator workflow her PR'da çalışmalıdır.",
            "Model cache checksum anahtarına bağlı olmalıdır.",
            "Model indirmeleri SHA256 doğrulamasından geçmelidir.",
            "Flutter unit testleri başarısızsa build durmalıdır.",
            "Flutter analyze hatası varsa build durmalıdır.",
            "Kotlin compile hatası varsa APK build durmalıdır.",
            "Debug APK build hatası kabulü durdurmalıdır.",
            "Release APK build hatası kabulü durdurmalıdır.",
            "AudioSocket modülü yoksa çağrı E2E durmalıdır.",
            "Whisper transcript beklenen Türkçe tokenları içermelidir.",
            "Piper dönüş sesi minimum byte ve RMS eşiğini geçmelidir.",
            "Arayan kanal kaydı minimum süre ve RMS eşiğini geçmelidir.",
            "Emülatör call answer sonucu success olmalıdır.",
            "Emülatör hangup sonucu success olmalıdır.",
            "Kabul kataloğu en az 250 benzersiz madde içermelidir.",
        ],
    ),
    (
        "release_observability",
        "release",
        "automated",
        [
            "Release artifact adı mimariyi açıkça belirtmelidir.",
            "Release artifact gerçek dosya boyutunu raporlamalıdır.",
            "Release artifact SHA256 raporlamalıdır.",
            "Release yalnız yeşil test commitinden üretilmelidir.",
            "PR açıklaması gerçek çalışan ve eksik alanları ayırmalıdır.",
            "Sahte carrier AI handover ifadesi release notunda bulunmamalıdır.",
            "Çağrı köprüsü deployment ortam değişkenleri belgelenmelidir.",
            "Kullanıcıya gerekli Android rollerinin listesi verilmelidir.",
            "Gerçek cihaz test sonucu commit SHA ile bağlanmalıdır.",
            "Main merge yalnız master acceptance sonucu yeşil olduğunda yapılmalıdır.",
        ],
    ),
]


def requirements() -> list[Requirement]:
    result: list[Requirement] = []
    number = 1
    for category, gate, level, descriptions in _GROUPS:
        for description in descriptions:
            result.append(
                Requirement(
                    id=f"NOVA-{number:03d}",
                    category=category,
                    description=description,
                    gate=gate,
                    level=level,
                )
            )
            number += 1
    return result


def as_jsonable(items: Iterable[Requirement] | None = None) -> list[dict[str, str]]:
    return [asdict(item) for item in (items or requirements())]


if __name__ == "__main__":
    import json

    data = as_jsonable()
    print(json.dumps({"count": len(data), "requirements": data}, ensure_ascii=False, indent=2))
